### ISSUE TITLE
Mqtt authentication - feature request

### ISSUE THREAD

**Issue by user-hash** [Vincenzo-Petrolo/MQTT-Joystick-Controller#1]
Hi,
very nice project, but could you add mqtt authentication for connection?
Thanks!

**Comment by Vincenzo-Petrolo** [comment]
Yeah, I will work on this and publish an update asap!

**Comment by user-hash** [comment]
Hey, the mqtt authentication is now working as it should!
I found 2 other problems when testing, if you need the feedback I can post the issues.

**Comment by Vincenzo-Petrolo** [comment]
Hi there, glad it is working! Open the issues for sure! :)
