### ISSUE TITLE
Textview label written inside textview text

### ISSUE THREAD

**Issue by FraioVeio** [Vincenzo-Petrolo/MQTT-Joystick-Controller#2]
The label of each textbox should not be the text of the textbox, but something like the suggested text (i can't write lol).
Currently you have to delete this text and once deleted there is no way to know wich textbox is wich.

**Comment by Vincenzo-Petrolo** [comment]
Hi @FraioVeio , you are right. Gonna work on this and plublish an update as soon as possible
