### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by MarosMotaj** [Vincenzo-Petrolo/MQTT-Joystick-Controller#7]
Hi, nice work, but today is not working on "broker.emqx.io" why? Thanks :)

**Comment by Vincenzo-Petrolo** [comment]
Hello, i think it is not a problem of the application but rather of the broker.

**Comment by MarosMotaj** [comment]
I have to use "broker.emqx.io" because the eclipse broker is not working yet. When I insert "broker.emqx.io" to app it will connect, but no data comes to subscriber on topic. I have to change something in program? Thanks :)

**Comment by Vincenzo-Petrolo** [comment]
No, i think the issue is related to your broker configuration.
